### PR TITLE
Refactor src and test directories

### PR DESCRIPTION
**Pull request by lewisdaly**
This PR changes the directory structure of this project to bring it into line with the other projects.

## The main changes are:
- moving `src` and `test` to the root directory and updating dockerfiles accordingly
- replacing the bespoke config with `rc`, which we use across the entire mojaloop codebase
- changing tab with from 4 spaces to 2

## Why should we refactor?
- Moving the `package.json` to the root of the project makes docker layer caching much more effective - we won't need to reinstall all of the `node_modules` every time a file is changed in src
- Moving out the test sources into the root dir means we can more easily build a 'production' docker image that doesn't contain test sources
- the `rc` library makes configuring the environment more easy and consistent
- in general, this will make switching between other projects and this one much more easy (including the fact that we can keep the ci config mostly consistent for this project)

Please let me know your thoughts/concerns/arguments for and against.

Please ignore CI/CD checks at this stage, we need this refactor first before working on those. The unit tests are passing locally, and the server(s) are spinning up just fine.

### CODE REVIEW

**Review by bushjames — COMMENTED** [review]
I have issues with pretty much all of this to be honest. I dont like the addition of rc - it is an unnecessary additional dependency; env vars are the ONLY way this code is intended to be configured i.e. it should not be run outside a container. Ever. So 90% of the rc code added is redundant from the start. Two space indent drastically hampers readability in my opinion vs 4 space indents. Multi-stage docker builds are the way to improve caching of node_modules, not moving source into the root of the repo, which means code gets mixed with other artefacts, further hampering the "understandability" of the repo layout.

This is working code as it is. I am personally not in agreement with the policy of Mojaloop re-styling code submissions. I have seen regressions creep in due to these activities in the past. I think efforts would be better spent in other ways.

**Comment by mdebarros** [comment]
> This is working code as it is. I am personally not in agreement with the policy of Mojaloop re-styling code submissions. I have seen regressions creep in due to these activities in the past. I think efforts would be better spent in other ways.

I do not agree. This is why we have QA (tests, etc), and it is also a good reason that we want consistency within Mojaloop...exactly to combat regression creep.

**Comment by bushjames** [comment]
You disagree that it is working code? Or that efforts are best spent elsewhere?

**Comment by lewisdaly** [comment]
Thanks @bushjames and @mdebarros for your comments - I thought this might be a hot topic. 

I think we're all on the same page in that we want to maintain a high quality codebase, but not yet in agreement on what that looks like.

As an OSS community, we need to establish some guidelines, preferences and best practices in this area, and as this is one of the first big contributions it's natural that we're going to run into some tensions here. 

I'm going to go ahead and close this PR here, and follow up this conversation inside of the DA, where we can break apart the changes that I was proposing to make, and make cases for and against each.

**Pull request closed without merging**
