### PR TITLE
feat(2151): helm-release-v12.1.0

### PR DESCRIPTION
**Pull request by mdebarros**
- Updated dependencies
- Fixes for updated dependencies
    - SQLite requiring the most refactoring --> ref: https://github.com/kriasoft/node-sqlite/blob/master/CHANGELOG.md#401---sat-apr-04-2020-214639. 
    - Added SQLite3 as a dependency.
    - Fixes import issues for UUID dependency --> ref: https://github.com/uuidjs/uuid#upgrading-from-uuid3.
    - Fixes to validate lib due to json-rules-engine dependency upgrade --> https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md#400--2019-08-22
- Bump patch version
- Fixed lint issues
- Added dep:check/update scripts for main project, libs, and added "all" variant using npm-run-all

### CODE REVIEW

**Comment by mdebarros** [comment]
I am not 100% this PR is LGTM yet, I suspect that the `json-rules-engine` breaking changes are quite extensive and are not fully dated by existing tests -> https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md.

Going to create a temp docker image for this, and run some tests on OSS environments to see if I can pick up any issues.

**Comment by mdebarros** [comment]
> I am not 100% this PR is LGTM yet, I suspect that the `json-rules-engine` breaking changes are quite extensive and are not fully dated by existing tests -> https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md.
> 
> Going to create a temp docker image for this, and run some tests on OSS environments to see if I can pick up any issues.

```
{
app: 'simulator',
request: { id: 'amuck-glove-accurate-fairies', path: '/', method: 'GET' },
response: {
body: { message: 'events.map is not a function', statusCode: 400 },
status: 400
},
msg: 'Request processed',
timestamp: '2021-06-08T09:02:39.832Z'
}
```

The issue is most likely here --> https://github.com/mojaloop/mojaloop-simulator/blob/master/src/lib/rules-engine/index.js#L80. Which is due to the breaking changes introduced by upgrading `json-rules-engine` dependency.

**Comment by mdebarros** [comment]
> I am not 100% this PR is LGTM yet, I suspect that the `json-rules-engine` breaking changes are quite extensive and are not fully dated by existing tests -> https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md.
> 
> Going to create a temp docker image for this, and run some tests on OSS environments to see if I can pick up any issues.

Also had to address the error below:
```
Error: Cannot find module 'openapi-jsonschema-parameters'
Require stack:
- /src/lib/validate/index.js
- /src/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
at Function.Module._load (internal/modules/cjs/loader.js:863:27)
at Module.require (internal/modules/cjs/loader.js:1043:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous> (/src/lib/validate/index.js:27:28)
at Module._compile (internal/modules/cjs/loader.js:1157:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
at Module.load (internal/modules/cjs/loader.js:1001:32)
at Function.Module._load (internal/modules/cjs/loader.js:900:14)
at Module.require (internal/modules/cjs/loader.js:1043:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/src/lib/validate/index.js', '/src/index.js' ]
}
```

`npm install --production` does not install the `openapi-jsonschema-parameters` dependency from the lib/validate library even though it is in the package-lock.json.

**Comment by mdebarros** [comment]
> I am not 100% this PR is LGTM yet.
> 

Also had to address the error below:
```
Error: Cannot find module 'openapi-jsonschema-parameters'
Require stack:
- /src/lib/validate/index.js
- /src/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
at Function.Module._load (internal/modules/cjs/loader.js:863:27)
at Module.require (internal/modules/cjs/loader.js:1043:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous> (/src/lib/validate/index.js:27:28)
at Module._compile (internal/modules/cjs/loader.js:1157:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
at Module.load (internal/modules/cjs/loader.js:1001:32)
at Function.Module._load (internal/modules/cjs/loader.js:900:14)
at Module.require (internal/modules/cjs/loader.js:1043:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/src/lib/validate/index.js', '/src/index.js' ]
}
```

`npm install --production` does not install the `openapi-jsonschema-parameters` dependency from the lib/validate library even though it is in the package-lock.json.

**Comment by mdebarros** [comment]
TTK Tests are all passing: 
```
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 1568                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 1568                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 299                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 61                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 08 Jun 2021 09:58:50 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 08 Jun 2021 10:00:23 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 93167 ms                      │
└───────────────────┴───────────────────────────────┘
```

**Comment by mdebarros** [comment]
> I am not 100% this PR is LGTM yet, I suspect that the `json-rules-engine` breaking changes are quite extensive and are not fully dated by existing tests -> https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md.
> 
> Going to create a temp docker image for this, and run some tests on OSS environments to see if I can pick up any issues.

Tested using OSS dev3 environment. Fixed all errors/issues that I was able to find. It LGTM now! \:D/

TTK GP Tests are all passing using `mdebarros/mojaloop-simulator:11.4.3-snapshot.4`
```
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 1568                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 1568                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 299                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 61                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 08 Jun 2021 09:58:50 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 08 Jun 2021 10:00:23 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 93167 ms                      │
└───────────────────┴───────────────────────────────┘
```

**Review by vijayg10 — APPROVED** [review]

**Pull request merged**
