### PR TITLE
feat!: update backend simulator api

### PR DESCRIPTION
**Pull request by kleyow**

### CODE REVIEW

**Comment by kleyow** [comment]
Tested with [13.1.3-snapshot.6]
```
--------------------FINAL REPORT--------------------

Test Suite:GP Tests
Environment:moja5.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 598                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 130                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 16 Dec 2022 05:06:18 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Fri, 16 Dec 2022 05:09:42 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 203881 ms                     │
└───────────────────┴───────────────────────────────┘
Successfully uploaded the file to S3. URL is s3://mojaloop-oss-qa-results/ttk-tests/reports/TTK-Assertion-Report-multi-2022-12-16T05:09:42.286Z.html

Test Suite:Bulk Tests
Environment:moja5.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 337                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 337                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 54                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 13                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 16 Dec 2022 05:09:54 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Fri, 16 Dec 2022 05:12:01 GMT │
├───────────────────┼───────────────────────────────┤

--------------------FINAL REPORT--------------------

Test Suite:Thirdparty Tests
Environment:moja5.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 20                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 8                             │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 16 Dec 2022 05:13:03 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Fri, 16 Dec 2022 05:13:14 GMT │
├───────────────────┼───────────────────────────────┤


Test Suite:SDK Bulk Tests
Environment:moja5.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 195                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 195                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 33                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 18                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 16 Dec 2022 05:14:15 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Fri, 16 Dec 2022 05:16:29 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 133495 ms                     │
```

**Comment by elnyry-sam-k** [comment]
Thanks Kevin for the PR and test results

Seems like a breaking change though..

**Comment by kleyow** [comment]
@elnyry-sam-k Nothing really should break. Mostly renaming variables that a user wouldn't have access to. 
Maybe rules might need to you rename the sub id but since the simulator is mostly ephermeral in nature I didn't think it needed it.

But I'll make it a breaking change since it is a big change to api file (mostly sorting though)

**Review by elnyry-sam-k — APPROVED** [review]

**Comment by elnyry-sam-k** [comment]
Seeing the changes - changes to column names in DB or API resources are breaking so flagged them.. Thanks for the change..

**Pull request merged**
