### PR TITLE
Update pipeline

### PR DESCRIPTION
**Pull request by akfranco**
- Update Python dependencies to Python 3
- Create a parallelized build pipeline that executes all Mojaloop standard processes (unit testing, auditing of built images, etc)

### CODE REVIEW

**Comment by partiallyordered** [comment]
@KamuelaFranco could you please provide a little motivation so I can contextualise what I'm looking at? I _guess_ it's
> bringing this repo more in line with other ML repos, while tidying/updating

?

**Comment by akfranco** [comment]
> @KamuelaFranco could you please provide a little motivation so I can contextualise what I'm looking at? I _guess_ it's
> 
> > bringing this repo more in line with other ML repos, while tidying/updating
> 
> ?

@msk- Yes, in preparation to bring on more steps that will build and publish our onboarding stories

**Comment by partiallyordered** [comment]
Is there something better to compare the CI config file to than the existing one? One from another repo or something? If you can point me at a file that this is more similar to, it'll make the diff a lot easier. Specifically, if you copied the CI config file in this PR from another repo, maybe point me at that repo and I'll diff against that instead of this. If not, that's fine, I'll dive in.

**Comment by akfranco** [comment]
> Is there something better to compare the CI config file to than the existing one? One from another repo or something? If you can point me at a file that this is more similar to, it'll make the diff a lot easier. Specifically, if you copied the CI config file in this PR from another repo, maybe point me at that repo and I'll diff against that instead of this. If not, that's fine, I'll dive in.

@msk- [mojaloop/reporting's config.yml](https://github.com/mojaloop/reporting/blob/master/.circleci/config.yml)

**Review by partiallyordered — APPROVED** [review]
Well. If I'm honest, I don't really believe in the idea of a "standardised build pipeline". But whatever.

Edit: that seems mean. I just didn't like reviewing this because it's busy and messy and kinda awful and we have to copy-paste a ton of stuff between repos and that's not ideal and it's not your fault what you've done is worthwhile.

**Comment by akfranco** [comment]
> Well. If I'm honest, I don't really believe in the idea of a "standardised build pipeline". But whatever.

I suppose I could buy into that as well. It just means that I'd have to read this one and learn it, and then improve it on its own terms. Sounds like a lot of wasted time, but maybe so is reviewing PR's like this.

**Pull request merged**
